// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfWfjTkzqlxTE_OsPzGkCv7SBVNJ5LJ3o',
    appId: '1:401854474569:web:3a1a0478c4c1ab4cebd298',
    messagingSenderId: '401854474569',
    projectId: 'spotify-7a829',
    authDomain: 'spotify-7a829.firebaseapp.com',
    storageBucket: 'spotify-7a829.appspot.com',
    measurementId: 'G-SLXWG01HC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATaKiv0R4d34M7af2e_oFxI6fXvaF4CDc',
    appId: '1:401854474569:android:2d305714f1ee92c9ebd298',
    messagingSenderId: '401854474569',
    projectId: 'spotify-7a829',
    storageBucket: 'spotify-7a829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBhWcNuz5hz8aO3_f4BMt_nPgnklFKHy4',
    appId: '1:401854474569:ios:0c6c301263c2091eebd298',
    messagingSenderId: '401854474569',
    projectId: 'spotify-7a829',
    storageBucket: 'spotify-7a829.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBhWcNuz5hz8aO3_f4BMt_nPgnklFKHy4',
    appId: '1:401854474569:ios:0c6c301263c2091eebd298',
    messagingSenderId: '401854474569',
    projectId: 'spotify-7a829',
    storageBucket: 'spotify-7a829.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfWfjTkzqlxTE_OsPzGkCv7SBVNJ5LJ3o',
    appId: '1:401854474569:web:35c6542f92e67d7cebd298',
    messagingSenderId: '401854474569',
    projectId: 'spotify-7a829',
    authDomain: 'spotify-7a829.firebaseapp.com',
    storageBucket: 'spotify-7a829.appspot.com',
    measurementId: 'G-2FEBK4M7V0',
  );

}